# local配置
local:
  enable: true
  primary: MASTER
  client:
    MASTER:
      permission: public
      path: /data/files/master
      api: /file/download/resource
    # SLAVE:
    #   path: /data/files/slave

# Minio配置
minio:
  enable: false
  primary: MASTER
  client:
    MASTER:
      permission: public
      url: http://localhost:9000
      accessKey:
      secretKey:
      bucketName: ruoyi
    # SLAVE:
    #   url: http://127.0.0.1:9000
    #   accessKey:
    #   secretKey:
    #   bucketName: ry

# oss配置
oss:
  enable: false
  primary: MASTER
  client:
    MASTER:
      permission: public
      accessKeyId: accessKeyId
      accessKeySecret: accessKeySecret
      bucketName: ruoyi
      endpoint: oss-cn-beijing.aliyuncs.com
    # SLAVE:
    #   accessKeyId: 
    #   accessKeySecret: 
    #   bucketName: 
    #   endpoint:


