# 请输入自己的appid和appsecret
wx:
  miniapp:
    open: true
    appId: miniAppid
    appSecret: miniAppSercret
    url: https://api.weixin.qq.com/sns/jscode2session
  h5:
    open: true
    appId: h5AppId
    appSecret: h5Secret
    url: https://api.weixin.qq.com/sns/oauth2/access_token