pay:
  sqb:
    enabled: false
    apiDomain: "apiDomain"
    terminalSn: "terminalSn"
    terminalKey: "terminalKey"
    appId: "appId"
    vendorSn: "vendorSn"
    vendorKey: "vendorKey"
  alipay:
    enabled: false
    appId: appId
    appPrivateKey: appPrivateKey #classpath:pay/alipay/alipay_private_key.pem
    alipayPublicKey: alipayPublicKey #classpath:pay/alipay/alipay_public_key.pem
    notifyUrl: http://www.sdaizy.com/prod-api/alipay/notify
  wechat:
    enabled: false
    merchantId: merchantId
    privateKeyPath: privateKeyPath # classpath:pay/wx/apiclient_key.pem
    merchantSerialNumber: merchantSerialNumber
    apiV3Key: apiV3Key
    appId: appId
    notifyUrl: http://g5vdrz.natappfree.cc/wxPay/notify
