# oss配置
oss:
    enable: false
    primary: MASTER
    client:
      MASTER:
        accessKeyId: 
        accessKeySecret: 
        bucketName: szb-resource
        endpoint: oss-cn-shenzhen.aliyuncs.com
