spring:
  data:
  #配置rabbitMq 服务器
  rabbitmq:
    enable: false
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


netty:
  websocket:
      maxMessageSize: 65536
      bossThreads: 4
      workerThreads: 16
      port: 8081
      enable: false
